import type { Metadata } from "next";
import { Noto_Naskh_Arabic } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";



const noto = Noto_Naskh_Arabic({ subsets: ["arabic"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <body className={noto.className}>
       {children}
      </body>
    </html>
  );
}
